### ISSUE TITLE
This change will require some downstream changes, namely updating keys to match the new prefixes. Here are the ones I know need to be changed:

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-functions#1]
I don't know if anyone uses this repo, but it has [a couple deprecated URLs](https://github.com/ChildMindInstitute/mindlogger-functions/blob/f7312c5e25001c575d4183e360fd90eaa5496a58/mit_voice_pilot/main.py#L17-L18)

_Originally posted by @shnizzedy in https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/207#issuecomment-547973883_

**Comment by binarybottle** [comment]
I believe this single commit was Anisha's attempt to dig into HBN data 9 months back.  I'm going to archive this repo.
